name: Reservation Monitor

on:
  schedule:
    - cron: "3,13,23,33,43,53 * * * *"

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  check-slots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check available slots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py